### ISSUE TITLE
Local overrides

### ISSUE THREAD

**Issue by l15n** [taiki45/denv#2]
Any chance of getting local overrides implemented?

i.e. The  `.env.local` facility provided by [dotenv](https://github.com/bkeepers/dotenv#multiple-rails-environments).

Local overrides are quite useful for individual credentials and other secrets.

**Comment by taiki45** [comment]
In Rails application, denv already loads `.env.local`. But I noticed denv should loads `.env` first, then loads `.env.local` to overwrite variables.

In non-Rails application, you can do by calling `Denv.load(filename)` multiple times with file names.

**Comment by taiki45** [comment]
https://github.com/taiki45/denv/pull/3 will fix this.

**Comment by taiki45** [comment]
Released as v0.2.5.

**Comment by taiki45** [comment]
I think this has been resolved. Please re-open if not.
